[package]
name = "amm"
version.workspace = true
edition.workspace = true

[dependencies]
scrypto = { workspace = true }
scrypto_math = { workspace = true}
off_ledger = { path = "../off_ledger" }
common = { path = "../common" }

[dev-dependencies]
scrypto-test = { version = "1.2.0" }
radix-transactions = { version = "1.2.0" }
test-case = "3.0"

[features]
default = []
test = []

[lib]
crate-type = ["cdylib", "lib"]
